controllers:
    resource: ../src/Controller/
    type: attribute

create_user:
    path: /register
    controller: App\Controller\RegistrationController::register
    methods: ['POST']
    defaults:
        _format: json

login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: ['POST']
    defaults:
        _format: json

add_book:
    path: /books/add_book
    controller: App\Controller\BookController::addBook
    methods: ['POST']
    defaults:
        _format: json

add_book_manual:
    path: /books/add_book_manual
    controller: App\Controller\BookController::addBookManual
    methods: ['POST']

book_image:
    path: /books/{id}/image
    controller: App\Controller\BookController::getBookImage
    methods: ['GET']

get_books:
    path: /books/
    controller: App\Controller\BookController::getBooks
    methods: ['GET']
    requirements:
        isbn: '\d+'

get_all_books:
    path: /books/available
    controller: App\Controller\BookController::getMainAvailableBooks
    methods: ['GET']
    defaults:
        _format: json

book_history:
    path: /books/{id}/history
    controller: App\Controller\BookController::getBookHistory
    methods: [GET]
    requirements:
        id: '\d+'

book_remove:
    path: /books/{id}
    controller: App\Controller\BookController::removeBook
    methods: [ POST ]
    requirements:
        id: '\d+'

book_update:
    path: /books/{id}
    controller: App\Controller\BookController::updateBook
    methods: [ PUT ]
    requirements:
        id: '\d+'

book_lend_list:
    path: /books/available_isbn/{isbn}
    controller: App\Controller\BookController::getAvailableBooks
    methods: ['GET']
    requirements:
        isbn: '\d+'

book_lend_request:
    path: /books/available/{id}
    controller: App\Controller\RequestsController::requestBook
    methods: [ POST ]
    requirements:
        id: '\d+'

book_request_list:
    path: /books/requests
    controller: App\Controller\RequestsController::getBookRequests
    methods: ['GET']
    defaults:
        _format: json

book_lend_request_accept:
    path: /books/requests/{id}/accept
    controller: App\Controller\RequestsController::acceptRequest
    methods: [ POST ]
    requirements:
        id: '\d+'

book_lend_request_decline:
    path: /books/requests/{id}/decline
    controller: App\Controller\RequestsController::declineRequest
    methods: [ POST ]
    requirements:
        id: '\d+'

book_lent:
    path: /books/lent
    controller: App\Controller\BookController::getLentBooks
    methods: ['GET']
    defaults:
        _format: json

book_lent_return:
    path: /books/lent/{id}/return
    controller: App\Controller\BookController::returnBook
    methods: [ POST ]
    requirements:
        id: '\d+'

book_returned:
    path: /books/returned
    controller: App\Controller\BookController::getReturnedBooks
    methods: ['GET']
    defaults:
        _format: json

book_return_accept:
    path: /books/lent/{id_book}/{id_user}/{id_request}/accept
    controller: App\Controller\RequestsController::acceptRequest
    methods: [ POST ]

get_user:
    path: /users/{id}/
    controller: App\Controller\UserController::getUserInfo
    methods: ['GET']
    defaults:
        _format: json

set_user_status:
    path: /users/{id}/toggle-status
    controller: App\Controller\UserController::setUserStatus
    methods: [ 'POST' ]
    requirements:
        id: '\d+'

report_person:
    path: /users/report
    controller: App\Controller\UserController::reportPerson
    methods: [ 'POST' ]

get_role:
    path: /user/role
    controller: App\Controller\UserController::getUserRole
    methods: [ 'GET' ]

my_lent:
    path: /books/my_lent
    controller: App\Controller\BookController::getMyLentBooks
    methods: [ 'GET' ]

expired_requests:
    path: /requests/expired
    controller: App\Controller\RequestsController::getExpiredRequests
    methods: [ 'GET' ]

accept_return:
    path: /reports/{id}/accept
    controller: App\Controller\UserController:acceptReport
    methods: [ 'POST' ]
    requirements:
        id: '\d+'

decline_return:
    path: /reports/{id}/decline
    controller: App\Controller\UserController:declineReport
    methods: [ 'POST' ]
    requirements:
        id: '\d+'
